---
- name: "provision a dev home away from home"
  hosts: all
  remote_user: vagrant

  tasks:
    - name: "apt-get update if it has been more than an hour"
      sudo: yes
      apt: update_cache=yes cache_valid_time=3600

    - name: "install common packages"
      sudo: yes
      apt: pkg={{ item }} state=present
      with_items:
        - avahi-daemon
        - build-essential
        - curl
        - emacs24-nox
        - firefox-esr
        - git
        - htop
        - mercurial
        - ntp
        - tig
        - tree
        - vim-nox
        - wget

    - name: "set timezone variables"
      sudo: yes
      copy: content='America/Chicago' dest=/etc/timezone owner=root group=root mode=0644
      notify:
        - update timezone

    - name: "start avahi-daemon/ntp on boot"
      sudo: yes
      service: name={{ item }} state=started enabled=yes
      with_items:
        - avahi-daemon
        - ntp

    - include: tasks/ssh.yml
    - include: tasks/minimal-lubuntu.yml
      tags: [xorg,lxde]
    - include: tasks/i3-wm.yml
      tags: [xorg,i3-wm]
    - include: tasks/virtualbox.yml
    - include: tasks/ruby.yml
      tags: [ruby]
    - include: tasks/nodejs.yml
      tags: [nodejs]
    - include: tasks/java.yml
      tags: [java]
    - include: tasks/dev-tools.yml

  handlers:
    - name: update timezone
      sudo: yes
      command: dpkg-reconfigure --frontend noninteractive tzdata
