---
  - name: "devtools | creates ~/{bin,code}"
    file: path=/home/vagrant/{{ item }} state=directory
    with_items:
      - bin
      - code

  - name: "devtools | download utility belt"
    get_url: url={{ item.url }} dest=/home/vagrant/bin/{{ item.alias }}
    with_items: devtools.utilities

  - name: "devtools | make tools executable"
    file: path=/home/vagrant/bin/{{ item.alias }} state=touch mode="u+x"
    with_items: devtools.utilities

  - name: "devtools | pull dotfiles"
    hg: repo=https://bitbucket.org/tvjg/dotfiles dest=/home/vagrant/code/dotfiles force=no

  - name: "devtools | symlink dotfiles"
    shell: "/home/vagrant/code/dotfiles/install"
