---
  - name: 'desktop | install minimal gnome desktop'
    sudo: yes
    apt: pkg={{ item }} state=present
    with_items:
      - gdm
      - gnome-app-install
      - gnome-core
      - gnome-system-tools
      - gnome-terminal
      - xorg

  - name: "desktop | start gdm on boot"
    sudo: yes
    service: name={{ item }} state=started enabled=yes
    with_items:
      - gdm
